services:
  redis:
    image: redis:alpine
    container_name: redis_local_dev
    ports:
      - "6379:6379"
    restart: unless-stopped

  # api:
  #   build: # ⬅️ usa a pasta api como contexto
  #     context: ./api
  #     dockerfile: Dockerfile # (opcional, é o nome padrão)
  #   container_name: leaky_api
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - PORT=3000
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     - redis
  #   restart: unless-stopped
